gestionlicence/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('licence/', include('licence.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

licence/urls.py
from django.urls import path

from . import views

app_name = 'licence' #espace de travail pour differente application

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('utilisateur/add', views.new_utilisateur, name='new_utilisateur'),
    path('dsi/add', views.new_dsi, name='new_dsi'),
    path('metrique/add', views.new_metrique, name='new_metrique'),
    path('editeur/add', views.new_editeur, name='new_editeur'),
    path('logiciel/add', views.new_logiciel, name='new_logiciel'),
    path('tarif/add', views.new_tarif, name='new_tarif'),
    path('demande/add', views.new_demande, name='new_demande'),
    path('serveur/add', views.new_serveur, name='new_serveur'),
    path('logiciel', views.allLogiciel, name='getAllLogiciel'),
    path('logiciel/set/<int:pk>', views.setLogiciel, name='setLogiciel'),
    path('editeur', views.allEditeur, name='getAllEditeur'),
    path('editeur/set/<int:pk>', views.setEditeur, name='setEditeur'),
    path('utilisateur', views.allUtilisateur, name='getAllUtilisateur'),
    path('utilisateur/set/<int:pk>', views.setUtilisateur, name='setUtilisateur'),
    path('demande', views.allDemande, name='getAllDemande'),
    path('demande/set/<int:pk>', views.setDemande, name='setDemande'),
    path('demande/test', views.testDemande, name='testDemande'),
    path('test', views.testJS, name='testJS'),
    path('ajax/logiciel/<int:pk>', views.api_logiciel_id, name='api_logiciel_id'),
    path('ajax/dsi', views.all_dsi, name='all_dsi'),
    path('ajax/all', views.all_username, name='all_username'),
    path('ajax/metrique/<int:pk>', views.api_metrique_logiciel, name='api_metrique_logiciel'),
    path('ajax/demande', views.api_post_demande, name='api_post_demande'),
]

licence/models.py
import datetime

from django.db import models
from django.utils import timezone


class Editeur(models.Model):
    nom = models.CharField(max_length=400)
    def __str__(self):
        return self.nom


class Metrique(models.Model):
    type = models.CharField(max_length=400)
    def __str__(self):
        return self.type

class Logiciel(models.Model):
    nom = models.CharField(max_length=400)
    nbLicenceTotal = models.IntegerField()
    nbLicenceRestante = models.IntegerField()
    descriptif = models.CharField(max_length=400)
    uniteDeMesure = models.IntegerField()
    metrique = models.ForeignKey(Metrique, on_delete=models.CASCADE)
    editeur = models.ForeignKey(Editeur, on_delete=models.CASCADE)
    def __str__(self):
        return self.nom

class Tarif(models.Model):
    acquisition = models.IntegerField()
    descriptifAcquisition = models.CharField(max_length=400)
    majSupport = models.IntegerField()
    validite = models.DateField()
    perimetre = models.CharField(max_length=400)
    commentaire = models.CharField(max_length=400)
    logiciel = models.ForeignKey(Logiciel, on_delete=models.CASCADE)
    def __str__(self):
        return self.acquisition


class Dsi(models.Model):
    nom = models.CharField(max_length=400)
    def __str__(self):
        return self.nom


class Utilisateur(models.Model):
    cp = models.CharField(max_length=400)
    nom = models.CharField(max_length=400)
    prenom = models.CharField(max_length=400)
    mail = models.CharField(max_length=400)
    admin = models.BooleanField(default=False)
    entite = models.ForeignKey(Dsi, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.cp) + " " + self.nom + " " + self.prenom

class Serveur(models.Model):
    nom = models.CharField(max_length=400)
    physique = models.BooleanField()
    typeCpu = models.CharField(max_length=400)
    modele = models.CharField(max_length=400)
    cpu = models.IntegerField()
    cores = models.IntegerField()
    def __str__(self):
        return self.nom

class Demande(models.Model):
    statut = models.IntegerField()
    dateCreation = models.DateField()
    dateCloture = models.DateField()
    dateSouhaitee = models.DateField()
    projet = models.CharField(max_length=400)
    clientDDSI = models.CharField(max_length=400)
    droitUsageLogiciel = models.CharField(max_length=400)
    type = models.IntegerField()
    quantite = models.IntegerField()
    coreFactor = models.FloatField()
    information = models.CharField(max_length=400)
    logiciel = models.ForeignKey(Logiciel, on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    serveur = models.ForeignKey(Serveur, on_delete=models.CASCADE)
    dsi = models.ForeignKey(Dsi, on_delete=models.CASCADE)
    def __str__(self):
        return self.logiciel.nom

licence/forms.py
from django import forms

from .models import Utilisateur, Editeur, Logiciel, Tarif, Demande, Serveur, Metrique, Dsi

class UserForm(forms.ModelForm):

    class Meta:
        model = Utilisateur
        fields = ('cp', 'mail', 'nom', 'prenom', "entite", "admin")


class EditeurForm(forms.ModelForm):

    class Meta:
        model = Editeur
        fields = '__all__'

class LogicielForm(forms.ModelForm):
    class Meta:
        model = Logiciel
        fields = ('__all__')

class TarifForm(forms.ModelForm):
    class Meta:
        model = Tarif
        fields = '__all__'


class DemandeForm(forms.ModelForm):
    class Meta:
        model = Demande
        fields = '__all__'

class ServeurForm(forms.ModelForm):
    class Meta:
        model = Serveur
        fields = '__all__'

class DsiForm(forms.ModelForm):

    class Meta:
        model = Dsi
        fields = '__all__'

class MetriqueForm(forms.ModelForm):

    class Meta:
        model = Metrique
        fields = '__all__'

licence/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core import serializers
import logging
import json


# Create your views here.



from django.views import generic

from .models import Demande, Logiciel, Editeur, Utilisateur, Dsi, Metrique
from .forms import UserForm, DemandeForm, ServeurForm, TarifForm, LogicielForm, EditeurForm, MetriqueForm, DsiForm


def new_utilisateur(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            print("je suis valide")
            demande = form.save(commit=False)
            demande.save()

        else:
            print(form)
            print("je ne suis pas valide")
    else:
        form = UserForm()
    return render(request, 'licence/formUser.html', {'form': form})

def new_editeur(request):
    if request.method == "POST":
        form = EditeurForm(request.POST)

        if form.is_valid():
            editeur = form.save(commit=False)
            editeur.save()
    else:
        form = EditeurForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def new_logiciel(request):
    if request.method == "POST":
        form = LogicielForm(request.POST)

        if form.is_valid():
            logiciel = form.save(commit=False)
            logiciel.save()
    else:
        form = LogicielForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def new_tarif(request):
    if request.method == "POST":
        form = TarifForm(request.POST)

        if form.is_valid():
            tarif = form.save(commit=False)
            tarif.save()
    else:
        form = TarifForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def new_serveur(request):
    if request.method == "POST":
        form = ServeurForm(request.POST)

        if form.is_valid():
            serveur = form.save(commit=False)
            serveur.save()
    else:
        form = ServeurForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def new_demande(request):
    if request.method == "POST":
        form = DemandeForm(request.POST)

        if form.is_valid():
            demande = form.save(commit=False)
            demande.save()
    else:
        form = DemandeForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def new_dsi(request):
    if request.method == "POST":
        form = DsiForm(request.POST)

        if form.is_valid():
            dsi = form.save(commit=False)
            dsi.save()
    else:
        form = DsiForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def new_metrique(request):
    if request.method == "POST":
        form = MetriqueForm(request.POST)

        if form.is_valid():
            metrique = form.save(commit=False)
            metrique.save()
    else:
        form = MetriqueForm()
    return render(request, 'licence/formulaire.html', {'form': form})

def setLogiciel(request, pk):
    logiciel = get_object_or_404(Logiciel, id=pk)
    if request.method == "POST":
        form = LogicielForm(request.POST, instance=logiciel)
        if form.is_valid():
            logiciel = form.save(commit=False)
            logiciel.save()
            return redirect('/licence/logiciel')
    else:
        form = LogicielForm(instance=logiciel)
    return render(request, 'licence/formulaire.html', {'form': form, 'test': "test566"})

def setEditeur(request, pk):
    editeur = get_object_or_404(Editeur, id=pk)
    if request.method == "POST":
        form = EditeurForm(request.POST, instance=editeur)
        if form.is_valid():
            editeur = form.save(commit=False)
            editeur.save()
            return redirect('/licence/editeur')
    else:
        form = EditeurForm(instance=editeur)
    return render(request, 'licence/formulaire.html', {'form': form})

def setUtilisateur(request, pk):
    utilisateur = get_object_or_404(Utilisateur, id=pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance=utilisateur)
        if form.is_valid():
            utilisateur = form.save(commit=False)
            utilisateur.save()
            return redirect('/licence/utilisateur')
    else:
        form = UserForm(instance=utilisateur)
    return render(request, 'licence/formulaire.html', {'form': form})

def setDemande(request, pk):
    demande = get_object_or_404(Demande, id=pk)
    if request.method == "POST":
        form = DemandeForm(request.POST, instance=demande)
        if form.is_valid():
            demande = form.save(commit=False)
            demande.save()
            return redirect('/licence/demande')
    else:
        form = DemandeForm(instance=demande)
    return render(request, 'licence/formulaire.html', {'form': form})



def allLogiciel(request):
    objects = Logiciel.objects.all()
    colonnes = ["Nom du logiciel", "Nom de l'editeur", "Descriptif", "Nombre de licences totales", "Nombre de licences restantes"]
    return render(request, 'licence/allLogiciel.html', {'objects': objects, 'colonnes': colonnes, })

def allEditeur(request):
    objects = Editeur.objects.all()
    colonnes = ["Nom de l'éditeur"]
    return render(request, 'licence/allEditeur.html', {'objects': objects, 'colonnes': colonnes, })

def allUtilisateur(request):
    objects = Utilisateur.objects.all()
    colonnes = ["CP", "Nom", "Prenom", "Adresse mail", "Entité", "Admin"]
    return render(request, 'licence/allUtilisateur.html', {'objects': objects, 'colonnes': colonnes, })

def allDemande(request):
    objects = Demande.objects.all()
    colonnes = ["Logiciel", "Statut", "Projet", "Quantité", "Demandeur"]
    return render(request, 'licence/allDemande.html', {'objects': objects, 'colonnes': colonnes, })

def index(request):
    return render(request, 'licence/index.html')

def testDemande(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        form2 = DemandeForm(request.POST)

        if form.is_valid():
            utilisateur = form.save(commit=False)
            utilisateur.save()
    else:
        form = UserForm()
        form2 = DemandeForm()
    return render(request, 'licence/allforms.html', {'form': form, 'form2': form2})

class DetailView(generic.DetailView):
    model = Demande
    template_name = 'licence/detail.html'

def validate_username(request):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        nick_name = request.GET.get("nick_name", None)
        # check for the nick name in the database.
        if Friend.objects.filter(nick_name=nick_name).exists():
            # if nick_name found return not valid new friend
            return JsonResponse({"valid": False}, status=200)
        else:
            # if nick_name not found, then user can create a new friend.
            return JsonResponse({"valid": True}, status=200)

    return JsonResponse({}, status=400)

def testJS(request):
    editeurs = Editeur.objects.all();
    form = UserForm();
    form3 = DemandeForm();
    return render(request, 'licence/testJS.html', {'form': form, 'form3':form3, 'editeurs': editeurs})

def all_username(request):
    # request should be ajax and method should be GET.

    if request.is_ajax and request.method == "GET":
        my_queryset = Utilisateur.objects.all()
        result_list = list(my_queryset.values('nom'))
        return HttpResponse(json.dumps(result_list))

def all_dsi(request):
    # request should be ajax and method should be GET.

    if request.is_ajax and request.method == "GET":
        my_queryset = Dsi.objects.all()
        result_list = list(my_queryset.values('nom'))
        return HttpResponse(json.dumps(result_list))

def api_logiciel_id(request, pk):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":

        my_queryset = Logiciel.objects.filter(editeur=pk)
        result_list = list(my_queryset.values('nom', 'id'))
        return HttpResponse(json.dumps(result_list))

def api_all_editeur(request):
    # request should be ajax and method should be GET.

    if request.is_ajax and request.method == "GET":
        my_queryset = Editeur.objects.all()
        result_list = list(my_queryset.values('nom'))
        return HttpResponse(json.dumps(result_list))

def api_metrique_logiciel(request, pk):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":

        my_queryset = Logiciel.objects.filter(id=pk)
        print(my_queryset)
        result_list = list(my_queryset.values('metrique__type'))
        return HttpResponse(json.dumps(result_list))

def api_post_demande(request):
    if request.method == 'POST':
        # no need to do this
        # request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
        request_getdata = request.POST.get('getdata', None)
        # make sure that you serialise "request_getdata"
        print(JsonResponse(request_getdata))
        print(JsonResponse(request_getdata))

licence/templates/licence/NouvelleDemande.html
faire une sorte de stepper, en gardant les variables (par exemple logiciel, sans les .save), puis on les .save juste à la fin??

licence/templates/licence/allDemande.html
{% extends 'licence/base.html' %}





{% block content %}


<div class="table-wrapper">
  <div class="table-scroller last-cell-fixed dragscroll">
    <table class="table">
      <caption class="sr-only">Titre</caption>
      <thead class="thead thead-light">
        <tr>
            {% for colonne in colonnes %}
         <th scope="col"><div class="cell-inner">{{ colonne}}</div></th>
            {% endfor %}
          <td class="cell-placeholder" aria-hidden="true"><span></span></td>
          <th class="cell-fixed"><span class="sr-only">Actions</span></th>
        </tr>
      </thead>
         <tbody class="tbody">
         {% for object in objects %}
            <tr>
                <td><div class="cell-inner">{{ object.logiciel }}</div></td>
              <td><div class="cell-inner">{{ object.statut }}</div></td>
              <td><div class="cell-inner">{{ object.projet }}</div></td>
              <td><div class="cell-inner">{{ object.quantite }}</div></td>
              <td><div class="cell-inner">{{ object.utilisateur }}</div></td>

          <td class="cell-placeholder"><span></span></td>
          <td class="cell-fixed">
            <div class="btn-group dropdown">
              <div class="cell-inner">
                      <button class="btn btn-only-icon btn-transparent btn-favorite" onclick="location.href='{% url 'licence:setDemande' object.id %}'">
                <i class="icons-pencil icons-size-1x25" aria-hidden="true"></i>
              </button>
            </div>
          </td>
        </tr>
{% endfor %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

licence/templates/licence/allEditeur.html
{% extends 'licence/base.html' %}





{% block content %}


<div class="table-wrapper">
  <div class="table-scroller last-cell-fixed dragscroll">
    <table class="table">
      <caption class="sr-only">Titre</caption>
      <thead class="thead thead-light">
        <tr>
            {% for colonne in colonnes %}
         <th scope="col"><div class="cell-inner">{{ colonne}}</div></th>
            {% endfor %}
          <td class="cell-placeholder" aria-hidden="true"><span></span></td>
          <th class="cell-fixed"><span class="sr-only">Actions</span></th>
        </tr>
      </thead>
         <tbody class="tbody">
         {% for object in objects %}
            <tr>
                <td><div class="cell-inner">{{ object.nom }}</div></td>
          <td class="cell-placeholder"><span></span></td>
          <td class="cell-fixed">
            <div class="btn-group dropdown">
              <div class="cell-inner">
                      <button class="btn btn-only-icon btn-transparent btn-favorite" onclick="location.href='{% url 'licence:setEditeur' object.id %}'">
                <i class="icons-pencil icons-size-1x25" aria-hidden="true"></i>
              </button>
            </div>
          </td>
        </tr>
{% endfor %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

licence/templates/licence/allLogiciel.html
{% extends 'licence/base.html' %}





{% block content %}


<div class="table-wrapper">
  <div class="table-scroller last-cell-fixed dragscroll">
    <table class="table">
      <caption class="sr-only">Titre</caption>
      <thead class="thead thead-light">
        <tr>
            {% for colonne in colonnes %}
         <th scope="col"><div class="cell-inner">{{ colonne}}</div></th>
            {% endfor %}
          <td class="cell-placeholder" aria-hidden="true"><span></span></td>
          <th class="cell-fixed"><span class="sr-only">Actions</span></th>
        </tr>
      </thead>
         <tbody class="tbody">
         {% for object in objects %}
            <tr>
                <td><div class="cell-inner">{{ object.nom }}</div></td>
              <td><div class="cell-inner">{{ object.editeur }}</div></td>
              <td><div class="cell-inner">{{ object.descriptif }}</div></td>
              <td><div class="cell-inner">{{ object.nbLicenceTotal }}</div></td>
              <td><div class="cell-inner">{{ object.nbLicenceRestante }}</div></td>

          <td class="cell-placeholder"><span></span></td>
          <td class="cell-fixed">
            <div class="btn-group dropdown">
              <div class="cell-inner">
                      <button class="btn btn-only-icon btn-transparent btn-favorite" onclick="location.href='{% url 'licence:setLogiciel' object.id %}'">
                <i class="icons-pencil icons-size-1x25" aria-hidden="true"></i>
              </button>
            </div>
          </td>
        </tr>
{% endfor %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

licence/templates/licence/allUtilisateur.html
{% extends 'licence/base.html' %}





{% block content %}


<div class="table-wrapper">
  <div class="table-scroller last-cell-fixed dragscroll">
    <table class="table">
      <caption class="sr-only">Titre</caption>
      <thead class="thead thead-light">
        <tr>
            {% for colonne in colonnes %}
         <th scope="col"><div class="cell-inner">{{ colonne}}</div></th>
            {% endfor %}
          <td class="cell-placeholder" aria-hidden="true"><span></span></td>
          <th class="cell-fixed"><span class="sr-only">Actions</span></th>
        </tr>
      </thead>
         <tbody class="tbody">
         {% for object in objects %}
            <tr>
                <td><div class="cell-inner">{{ object.cp }}</div></td>
              <td><div class="cell-inner">{{ object.nom }}</div></td>
              <td><div class="cell-inner">{{ object.prenom }}</div></td>
              <td><div class="cell-inner">{{ object.mail }}</div></td>
              <td><div class="cell-inner">{{ object.entite }}</div></td>
                <td><div class="cell-inner">{{ object.admin }}</div></td>

          <td class="cell-placeholder"><span></span></td>
          <td class="cell-fixed">
            <div class="btn-group dropdown">
              <div class="cell-inner">
                      <button class="btn btn-only-icon btn-transparent btn-favorite" onclick="location.href='{% url 'licence:setUtilisateur' object.id %}'">
                <i class="icons-pencil icons-size-1x25" aria-hidden="true"></i>
              </button>
            </div>
          </td>
        </tr>
{% endfor %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

licence/templates/licence/allforms.html
{% extends 'licence/base.html' %}




{% block content %}
    <div class="actionbar has-tabs">
  <nav role="navigation" aria-label="Étapes" class="d-none d-md-flex">
    <ol class="breadcrumb mt-2 mb-0">
      <li class="breadcrumb-item active" aria-current="step"><a href="#">Utilisateur</a></li>
      <li class="breadcrumb-item disabled" ><a href="#">Projet</a></li>
      <li class="breadcrumb-item disabled"><a href="#">Serveur</a></li>
      <li class="breadcrumb-item disabled"><a href="#">Demande</a></li>
    </ol>
  </nav>
</div>

<br><br><br><br>
<form method="POST">
{% csrf_token %}
    {{ form.as_p}}
 <button class="btn btn-primary" type="submit">Submit form</button>
</form>



<form method="POST">
{% csrf_token %}
    {{ form2.as_p}}
 <button class="btn btn-primary" type="submit">Submit form</button>
</form>

{% endblock %}

licence/templates/licence/formUser.html
{% extends 'licence/base.html' %}

{% block javascript %}
  <script>
    $("#id_utilisateur").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: "{% url 'validate_username' %}",
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
          }
        }
      });

    });
  </script>
{% endblock %}


{% block content %}
<nav role="navigation" aria-label="Étapes" class="d-none d-md-flex">
    <ol class="breadcrumb mt-2 mb-0">
      <li class="breadcrumb-item active" aria-current="step"><a href="#">Logiciel</a></li>
        <li class="breadcrumb-item disabled" id="etape2"><a href="#">Utilisateur</a></li>
      <li class="breadcrumb-item disabled"><a href="#">Demande</a></li>
      <li class="breadcrumb-item disabled"><a href="#">Étape 4</a></li>
    </ol>
  </nav>
    <br>
<form method="POST" class="needs-validation" novalidate>
{% csrf_token %}
     <div class="form-row">
    <div class="col-md-4 mb-3">
      <label class="font-weight-medium mb-2 required" for="validationCustom01">CP</label>
      <div class="form-control-container">
          {{form.cp}}
        <span class="form-control-state"></span>
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label class="font-weight-medium mb-2 required" for="validationCustom02">Nom</label>
      <div class="form-control-container">
        {{form.nom}}
        <span class="form-control-state"></span>
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label class="font-weight-medium mb-2 required" for="validationCustomUsername">Prenom</label>
      <div class="form-control-container is-invalid">
        {{form.prenom}}
        <span class="form-control-state"></span>
      </div>
      <div class="invalid-feedback" id="inputGroupPrepend">
        Veuillez choisir un pseudo.
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label class="font-weight-medium mb-2 required" for="validationCustom03">Adresse mail</label>
      <div class="form-control-container is-invalid">
        {{form.mail}}
        <span class="form-control-state"></span>
      </div>
      <div class="invalid-feedback" id="inputGroupPrepend2">
        Veuillez renseigner une ville valable.
      </div>
    </div>
      <div class="col-md-4 mb-3">
      <label class="font-weight-medium mb-2 required" for="validationCustom02">Entite</label>
      <div class="form-control-container">
        {{form.entite}}
        <span class="form-control-state"></span>
      </div>
    </div>
  </div>
    <div class="form-row">
      {{form.admin}}
      <label class="font-weight-medium mb-2 required" for="validationCustom02">Admin</label>
    </div>
    </div>

<button class="btn btn-primary" type="submit">Submit form</button>
</form>



<script>

var element = document.getElementById('etape2');

var myFunction = function() {
    var xhr = new XMLHttpRequest();

    // On souhaite juste récupérer le contenu du fichier, la méthode GET suffit amplement :
    xhr.open('GET', 'http://127.0.0.1:8000/licence/ajax/all');
    xhr.responseType = "json";
    xhr.send();
    xhr.onprogress = function() {
        console.log("je charge");
    }
    xhr.onload = function () {
        data = JSON.stringify(xhr.response)

        data = JSON.parse(
            data
        )
        for (var i = 0; i < data.length; i++) {
    alert(data[i].nom);
}
    }
}


element.addEventListener('click', myFunction);

</script>


{% endblock %}

licence/templates/licence/index.html
{% extends 'licence/base.html' %}





{% block content %}

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Logiciel</h5>
        <p class="card-text">Vous pouvez créer ou modifier un logiciel existant</p>
        <a href="{% url 'licence:new_logiciel'%}" class="btn btn-primary">Créer</a> <a href="{% url 'licence:getAllLogiciel'%}" class="btn btn-primary">Modifier</a>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Editeur</h5>
        <p class="card-text">Vous pouvez créer ou modifier un éditeur existant</p>
        <a href="{% url 'licence:new_editeur'%}" class="btn btn-primary">Créer</a> <a href="{% url 'licence:getAllEditeur'%}" class="btn btn-primary">Modifier</a>
      </div>
    </div>
  </div>

<div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Utilisateur</h5>
        <p class="card-text">Vous pouvez créer ou modifier un utilisateur existant</p>
        <a href="{% url 'licence:new_utilisateur'%}" class="btn btn-primary">Créer</a> <a href="{% url 'licence:getAllUtilisateur'%}" class="btn btn-primary">Modifier</a>
      </div>
    </div>
  </div>

<div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Demande</h5>
        <p class="card-text">Vous pouvez créer ou modifier une demande existante</p>
        <a href="{% url 'licence:new_demande'%}" class="btn btn-primary">Créer</a> <a href="{% url 'licence:getAllDemande'%}" class="btn btn-primary">Modifier</a>
      </div>
    </div>
  </div>

<div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">DSI</h5>
        <p class="card-text">Vous pouvez créer ou modifier une dsi existante</p>
        <a href="{% url 'licence:new_dsi'%}" class="btn btn-primary">Créer</a>
      </div>
    </div>
  </div>


<div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Métrique</h5>
        <p class="card-text">Vous pouvez créer ou modifier une métrique existante</p>
        <a href="{% url 'licence:new_metrique'%}" class="btn btn-primary">Créer</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}